### PR TITLE
added opacity blender for rgba and opacity css attributes

### PR DESCRIPTION
**Pull request by DDKnoll**
Should improve the fixes in place for issues #10 and #11

### CODE REVIEW

**Comment by Rich-Harris** [comment]
Thanks, this is great! The rgba blending looks spiffy, and I would never have figured out that compositing formula. I've merged this in to the `opacity` branch, need to tidy up a few other things before it goes into `master`

**Comment by williammalo** [comment]
Doesn't changing the background color trigger a paint and make the animation slow? (This also applies to border radius) is there an option to disable it for  performance reasons?

**Comment by Rich-Harris** [comment]
@williammalo that's a very good point... it should probably auto-detect when it can use compositor-only features, and allow a `compositorOnly: true` option (suggestions for better names welcome)

**Comment by DDKnoll** [comment]
That is true.  Most of the time, I would prefer to drop a couple of frames on that animation than to have it look broken by skipping them. @Rich-Harris, good call on allowing them to be disabled with `compositorOnly: true`.

The way I wrote it, the backgroundColor will only be written to the keyframes when one of the nodes has a background alpha value less than 1 (the backgroundColors variables will be false if they don't need to animate.)  https://github.com/Rich-Harris/ramjet/blob/opacity/src/transformers/KeyframeTransformer.js#L99

We could do the same thing for border radius, where we only transition them when the elements have different border-radiuses.

**Pull request merged**
