### PR TITLE
Add support for passing jquery elements to wrapNode

### LINKED ISSUE #32: Support Jquery Selectors
Would be convenient to say:
```
ramjet.transform( $('#a'), $('#b') );
```

instead of currently having to verbosely convert jquery elements to their corresponding dom elements:
```
ramjet.transform( $('#a').get(0), $('#b').get(0) );
```

### PR DESCRIPTION
**Pull request by MrAlexLau**
Fixes #32. This PR is a little rough (no tests, didn't update any demo files) - let me know if you want me to add anything else.

### CODE REVIEW

**Comment by williammalo** [comment]
Does this work with nodelists as well?

**Comment by MrAlexLau** [comment]
@williammalo - by nodelists, you mean if `$('.some-selector')` matches more than one element? It does not, it naively picks the first element that matches the selector. 

The reason I opted for that is because it didn't seem to jive with the general purpose of ramjet to transform one element into another (not a list of elements into one).

**Comment by williammalo** [comment]
@MrAlexLau no, I mean https://developer.mozilla.org/en/docs/Web/API/NodeList

**Comment by MrAlexLau** [comment]
Ah, no it just handles jQuery elements.

**Comment by sithmel** [comment]
Hi, I don't think we should include this inside the library. Interoperability should work on DOM level. It is very easy using ramjet with jQuery doing:

    ramjet.transform( $('#a').get(0), $('#b').get(0) );

**Pull request closed without merging**
